domene: "app.adeo.no"
environment: "p"
kafka:
  pool: "nav-prod"
  removeDataWhenDeleted: "true"
secrets:
  env: "prod"
  namespace: ""
security:
  jwksUrl: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
  adminUsers: "U143410"

tasks:
  startProcessChanges:
    autoStart: "true"
  syncChangesInHenvendelse:
    autoStart: "true"